# Generated by Django 5.0.5 on 2025-05-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_store_produ_categor_b49ff2_idx_store_produ_categor_b51135_idx_and_more'),
        ('store', '0003_convert_category_to_foreignkey'),
    ]

    operations = [
    ]
