# Generated by Django 5.1.6 on 2025-02-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_available_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('neocaridina', 'Neocaridina Shrimp'), ('caridina', 'Caridina Shrimp'), ('floating_plants', 'Floating Plants'), ('stem_plants', 'Stem Plants'), ('rosette_plants', 'Rosette Plants'), ('botanicals', 'Botanicals'), ('food', 'Food'), ('merchandise', 'Merchandise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
