# Generated by Django 5.0.6 on 2025-06-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_improve_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image for display on the website', null=True, upload_to='categories/'),
        ),
    ]
