# Generated by Django 5.0.6 on 2025-07-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_categor_b49ff2_idx',
            old_name='prod_cat_avail_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'price'], name='store_produ_availab_937d20_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'stock'], name='store_produ_availab_56ed7b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'created_at'], name='store_produ_availab_c48911_idx'),
        ),
    ]
